using Raven.Core.Models.Rally;
using Raven.Core.Models.GitLab;

namespace Raven.Core.Workflow;

/// <summary>
/// Shared context passed through a RAVEN workflow.
/// Accumulates state as each agent contributes its output.
/// </summary>
public sealed class WorkflowContext
{
    /// <summary>
    /// The Rally work item being processed.
    /// </summary>
    public RallyWorkItem? WorkItem { get; set; }

    /// <summary>
    /// The target GitLab project for this workflow.
    /// </summary>
    public GitLabProject? TargetProject { get; set; }

    /// <summary>
    /// The branch created for this work item.
    /// </summary>
    public GitLabBranch? WorkBranch { get; set; }

    /// <summary>
    /// The merge request created for this work item.
    /// </summary>
    public GitLabMergeRequest? MergeRequest { get; set; }

    /// <summary>
    /// Files identified as affected by the work item.
    /// </summary>
    public List<string> AffectedFiles { get; set; } = [];

    /// <summary>
    /// Execution plan generated by the Planner agent.
    /// </summary>
    public ExecutionPlan? Plan { get; set; }

    /// <summary>
    /// Log of actions taken during the workflow.
    /// </summary>
    public List<WorkflowAction> Actions { get; set; } = [];

    public void LogAction(string agent, string action, string detail)
    {
        Actions.Add(new WorkflowAction(agent, action, detail, DateTime.UtcNow));
    }
}

public sealed record WorkflowAction(
    string Agent,
    string Action,
    string Detail,
    DateTime Timestamp);

public sealed class ExecutionPlan
{
    public string StoryId { get; set; } = string.Empty;
    public List<string> Tasks { get; set; } = [];
    public string Risk { get; set; } = "Unknown";
    public List<string> Dependencies { get; set; } = [];
    public double EstimatedHours { get; set; }
}
